nodeLinker: node-modules

npmPublishAccess: restricted

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  nigelng:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.16.0.cjs
